---
- name: Install mongodb component
  hosts: mongodb
  become: yes
  tasks:
  - name : copy mongo repo to yum.repos.d
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo
  - name : install mongodb
    ansible.builin.yum:
     name: mongodb-org
     state : installed
  - name : start and enable mongodb
    ansible.builtin.service:
     name: mongodb
     state: started
     enabled: yes
  - name : enabled remote connection to mongodb
    ansible.biultin.replace:
     path :  /etc/mongod.conf
     regexp : '127.0.0.1'
     replace : '0.0.0.0'
  - name : restart mongodb
    ansible.builtin.service:
     name : mongodb
     state : restarted
     